USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/htc/vivow/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_KERNEL_SOURCE := kernel/htc/msm-8960
TARGET_KERNEL_CONFIG := fighter_defconfig
TARGET_BOOTLOADER_BOARD_NAME := vivow

BOARD_KERNEL_CMDLINE := no_console_suspend=1
BOARD_KERNEL_BASE := 0x05000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00400000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x0087f400
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x22dffe00
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x496ffe00
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/htc/vivow/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
